# -*- coding: utf-8 -*-
{
    'name': 'IT Parc - Gestion de parc informatique',
    'version': '18.0.1.0.0',
    'category': 'IT / Informatique',
    'summary': 'Gestion complète du parc informatique.',
    'author': 'TECHPARK CI / IIT Grand-Bassam',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'hr',
        'maintenance',
        'purchase',
        'account',
        'stock',
        'web',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'views/it_equipement_views.xml',
        'views/it_affectation_views.xml',
        'views/it_intervention_views.xml',
        'views/it_contrat_views.xml',
        'views/it_alerte_views.xml',
        'wizards/wizard_reaffectation_views.xml',
        'wizards/wizard_import_csv_views.xml',
        'wizards/wizard_scan_alertes_views.xml',
        'wizards/wizard_rapport_maintenance_views.xml',
        'report/report_equipement.xml',
        'report/report_inventaire.xml',
        'report/report_maintenance.xml',
        'views/menu.xml',
    ],
    'demo': [
        'data/it_parc_demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_parc/static/src/components/it_dashboard/it_dashboard.js',
            'it_parc/static/src/components/it_dashboard/it_dashboard.xml',
            'it_parc/static/src/components/it_dashboard/it_dashboard.scss',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
}
